version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message: &commit
      prefix: "chore"
      include: "scope"
  - package-ecosystem: "docker"
    directory: "/src"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message: *commit
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message: *commit
