// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:1.0.0.0
//      Reqnroll Generator Version:1.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Arius.Core.BehaviorTests.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "1.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Restore from Archive Tier")]
    public partial class RestoreFromArchiveTierFeature
    {
        
        private Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
#line 1 "Restore_ArchiveTier.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(null, NUnit.Framework.TestContext.CurrentContext.WorkerId);
            Reqnroll.FeatureInfo featureInfo = new Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Restore from Archive Tier", "A short summary of the feature", ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await testRunner.OnFeatureEndAsync();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("B_Restore a file from archive tier")]
        [NUnit.Framework.CategoryAttribute("restore")]
        [NUnit.Framework.CategoryAttribute("archive")]
        public async System.Threading.Tasks.Task B_RestoreAFileFromArchiveTier()
        {
            string[] tagsOfScenario = new string[] {
                    "restore",
                    "archive"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("B_Restore a file from archive tier", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
 await testRunner.GivenAsync("a BinaryFile \"File3.txt\" of size \"ABOVE_ARCHIVE_TIER_LIMIT\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
 await testRunner.WhenAsync("archived to the Archive tier", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 9
 await testRunner.WhenAsync("copy the PointerFile of BinaryFile \"File3.txt\" to the restore directory", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 10
    await testRunner.WhenAsync("restore --download", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 12
 await testRunner.ThenAsync("the hydration for the chunks of BinaryFile \"File3.txt\" have started", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
#line 14
 await testRunner.ThenAsync("the BinaryFile \"File3.txt\" does not exist", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("A_Restore a file from archive tier after the chunk has been hydrated")]
        [NUnit.Framework.CategoryAttribute("restore")]
        [NUnit.Framework.CategoryAttribute("archive")]
        public async System.Threading.Tasks.Task A_RestoreAFileFromArchiveTierAfterTheChunkHasBeenHydrated()
        {
            string[] tagsOfScenario = new string[] {
                    "restore",
                    "archive"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("A_Restore a file from archive tier after the chunk has been hydrated", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 20
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 22
 await testRunner.GivenAsync("a BinaryFile \"File4.txt\" of size \"ABOVE_ARCHIVE_TIER_LIMIT\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 23
 await testRunner.WhenAsync("archived to the Cool tier", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 24
 await testRunner.WhenAsync("copy the PointerFile of BinaryFile \"File4.txt\" to the restore directory", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 25
 await testRunner.WhenAsync("the chunk of BinaryFile \"File4.txt\" is copied to the rehydrate folder and the ori" +
                        "ginal chunk is moved to the Archive tier", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 26
 await testRunner.WhenAsync("restore --download", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 28
 await testRunner.ThenAsync("the BinaryFile \"File4.txt\" exists", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
#line 29
 await testRunner.ThenAsync("the rehydrate folder does not exist", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
