// <auto-generated />
using System;
using Arius.Core.Shared.StateRepositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Arius.Core.Shared.StateRepositories.Migrations
{
    [DbContext(typeof(StateRepositoryDbContext))]
    partial class StateRepositoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Arius.Core.Shared.StateRepositories.BinaryProperties", b =>
                {
                    b.Property<byte[]>("Hash")
                        .HasColumnType("BLOB");

                    b.Property<long>("ArchivedSize")
                        .HasColumnType("INTEGER");

                    b.Property<long>("OriginalSize")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ParentHash")
                        .HasColumnType("BLOB");

                    b.Property<int>("StorageTier")
                        .HasColumnType("INTEGER");

                    b.HasKey("Hash");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.ToTable("BinaryProperties", (string)null);
                });

            modelBuilder.Entity("Arius.Core.Shared.StateRepositories.PointerFileEntry", b =>
                {
                    b.Property<byte[]>("Hash")
                        .HasColumnType("BLOB");

                    b.Property<string>("RelativeName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreationTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastWriteTimeUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Hash", "RelativeName");

                    b.HasIndex("Hash");

                    b.HasIndex("RelativeName");

                    b.HasIndex("RelativeName", "Hash")
                        .HasDatabaseName("IX_PointerFileEntries_RelativeName_Hash");

                    b.ToTable("PointerFileEntries", (string)null);
                });

            modelBuilder.Entity("Arius.Core.Shared.StateRepositories.PointerFileEntry", b =>
                {
                    b.HasOne("Arius.Core.Shared.StateRepositories.BinaryProperties", "BinaryProperties")
                        .WithMany("PointerFileEntries")
                        .HasForeignKey("Hash")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BinaryProperties");
                });

            modelBuilder.Entity("Arius.Core.Shared.StateRepositories.BinaryProperties", b =>
                {
                    b.Navigation("PointerFileEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
