name: Arius.Core - Test Suite

on:
  push:
    paths: 
      - 'src/Arius.Core/**'

jobs:
  job1:
    name: Run Test Suite
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: ./src

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: true # Check out WouterVanRanst.Utils

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x
          # include-prerelease: true

      - name: Test
        run: |
          dotnet test Arius.Core.Tests -l "console;verbosity=detailed" # -v normal #specified project with tests for wpf / windows / linux runner
          dotnet test Arius.Core.BehaviorTests -l "console;verbosity=detailed" # -v normal #specified project with tests for wpf / windows / linux runner
        #run: dotnet test -l "console;verbosity=detailed" # -v normal
        # continue-on-error: true
        env:
          ARIUS_ACCOUNT_NAME: ariusci
          ARIUS_ACCOUNT_KEY: ${{ secrets.ARIUS_ACCOUNT_KEY }}
          

