name: Arius.Core - Test & Release Nuget Package

on:
  # Runs when main gets a tag
  push:
    # paths:
    #   - 'src/Arius.Core/**'
    branches:
        - main
    tags:
      - 'v*'

jobs:
  job1:
    name: Release Nuget Package
    # if: startsWith(github.ref, 'refs/tags/') || (github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, 'v'))
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: ./src

    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        submodules: true # Check out WouterVanRanst.Utils

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x
        # include-prerelease: true

    - name: Test
      run: |
        dotnet test Arius.Core.BehaviorTests -c Release
        dotnet test Arius.Core.Tests -c Release
      env:
        ARIUS_ACCOUNT_NAME: ariusci
        ARIUS_ACCOUNT_KEY: ${{ secrets.ARIUS_ACCOUNT_KEY }}

    # Extract the version from the tag
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}

    - name: Pack
      run: dotnet pack Arius.Core -c Release --output . -p:PackageVersion=${{ steps.get_version.outputs.VERSION }}
    
    - name: Push
      run: dotnet nuget push *.nupkg --source https://nuget.pkg.github.com/woutervanranst --api-key ${GITHUB_TOKEN}
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
