name: Arius.Core - Test Suite

on:
  # Runs on every push to Arius.Core
  push:
    paths: 
      - 'src/Arius.Core/**'

jobs:
  test:
    name: Run Test Suite on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    defaults:
      run:
        working-directory: ./src

    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        submodules: true # Check out WouterVanRanst.Utils

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x

    - name: Install Coverlet for coverage report generation
      run: dotnet add package coverlet.msbuild

    # Cache NuGet packages
    - name: Cache .NET packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.nuget/packages
          !~/.nuget/packages/**/project.assets.json
          !~/.nuget/packages/**/project.nuget.cache
        key: ${{ runner.os }}-dotnet-${{ hashFiles('**/Arius.Core.csproj') }}
        restore-keys: |
          ${{ runner.os }}-dotnet-

    - name: Test
      run: |
        dotnet test Arius.Core.BehaviorTests /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
        dotnet test Arius.Core.Tests /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      env:
        ARIUS_ACCOUNT_NAME: ariusci
        ARIUS_ACCOUNT_KEY: ${{ secrets.ARIUS_ACCOUNT_KEY }}

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: |
          ./src/Arius.Core.BehaviorTests/coverage.opencover.xml
          ./src/Arius.Core.Tests/coverage.opencover.xml
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
