name: Arius.Core - Release Nuget Package

on:
  push:
    paths:
      - 'Arius/Arius.Core/**'
        

# See https://acraven.medium.com/a-nuget-package-workflow-using-github-actions-7da8c6557863
  ## See 'Set VERSION variable from tag'
# TODO https://dusted.codes/github-actions-for-dotnet-core-nuget-packages

jobs:
  job1:
    name: Release

    defaults:
      run:
        working-directory: ./Arius

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Build
      run: dotnet build Arius.Core --configuration Release
    
    - name: Test
      run: dotnet test Arius.Core.Tests --configuration Release --no-build
    
    - name: Pack
      run: dotnet pack Arius.Core --configuration Release --no-build --output .
    
    - name: Push
      run: dotnet nuget push *.nupkg --source https://nuget.pkg.github.com/woutervanranst --api-key ${GITHUB_TOKEN}
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}